### ISSUE TITLE
[BUG] undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[10], "react-native-vision-camera-face-detector").Camera

### ISSUE THREAD

**Issue by w3company-leo** [nonam4/react-native-vision-camera-face-detector#19] opened 2024-03-25 08:51 UTC
**Describe the bug**
In ios, error has occured when open camera,
android is work well

```
undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[10], "react-native-vision-camera-face-detector").Camera
```

**Smartphone (please complete the following information):**
 - Device: IPhone 15 pro
 - OS: ios 17.4
 - Vision Camera version: 3.9.1
 - Face detector version: 1.3.5

**Comment by nonam4** [comment] 2024-03-25 11:30
@w3company-leo I have a simillar (maybe is the same) issue on a client's iphone 15 pro max but the problem is I don't have an Iphone 15 to debug and fix this issue.  

Can you please provide me more details, logs so I can try fix this issue?
You can also open a PR with the fix

**Comment by w3company-leo** [comment] 2024-03-26 02:17
Both of way has same type of error
I just got error in module import

```
undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[10], "react-native-vision-camera-face-detector").Camera
```
```
Possible Unhandled Promise Rejection (id: 2):
TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[10], "react-native-vision-camera-face-detector").detectFaces')
```

**Comment by nonam4** [comment] 2024-03-26 15:40
can you provide a minimum reproducible example app?

**Comment by w3company-leo** [comment] 2024-04-01 02:53
I just use your example..

**Comment by nonam4** [comment] 2024-04-01 11:29
Sorry, I can't repro your issue so I'm closing this issue.

I would apretiate if you can open a PR with a fix for this problem.

**Closed by nonam4** 2024-04-01 11:29 UTC
Labels: bug, help wanted
